### ISSUE TITLE
Add meta tags for better iOS support

### ISSUE THREAD

**Issue by dotproto** [getify/cloud-sweeper#5]
According to Apple's docs, adding the following meta tag will allow full screen support when the user adds the site to the home screen.

```
<meta name="apple-mobile-web-app-capable" content="yes">
```

https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html

**Comment by getify** [comment]
also added the chrome manifest.json for installable web app config.
